create table transactions(
  id int4 primary key generated by default as identity,
  user_id integer references users(id) on delete cascade not null,
  date_added timestamp with time zone default now() not null,
  title text not null,
  amount int not null
);