create table transactions(
  id int4 primary key generated by default as identity,
  date_added timestamp with time zone default now() not null,
  title text not null,
  amount decimal not null,
  user_id integer references users(id) on delete cascade not null,
  category integer references category(id) on delete cascade not null
);